### ISSUE TITLE
Where is located the sqlite file? [Missing docker volume?]

### ISSUE THREAD

**Issue by Extarys** [vabene1111/recipes#155]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.0

### Issue
So, I lost my recipes today - no I didn't have a backup yet because I only had 5 recipes :P but I'm still mad at myself and docker.

I didn't use postgres, so I was under the impression the sqlite database was under `staticfiles` or `mediafiles`. I backup my `containers` folder daily.
I updated recipes to the latest version and now it's like it's a new install. I still have the old image so I guess they are in there somewhere.

1) Where is located the sqlite file? So I can store that file on the host
2) How can I log in the container to retrieve the database file? (I'm using portainer but I couldn't connect with the console)

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
services:
  recipes:
    image: vabene1111/recipes
    container_name: recipes
    ports:
      - "9286:8080"
    networks:
      public:
        ipv4_address: 172.18.0.10
    volumes:
      - /storage/containers/recipes/staticfiles:/opt/recipes/staticfiles
      - /storage/containers/recipes/mediafiles:/opt/recipes/mediafiles
    restart: unless-stopped
```

Side note: Overall though I very like recipes! I'm trying to cook more :D thanks for that it's helping a lot.
