### ISSUE TITLE
Missing buttons in recipe view

### ISSUE THREAD

**Issue by LBBO** [vabene1111/recipes#159]
First of all: thank you so much for this great project! It's been absolutely amazing to use and definitely exceeded the expectations I had when I started searching for recipe management systems.

### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.10.1; Ref https://github.com/vabene1111/recipes/commit/82497c734aa0c800642464d92cda3d1cb2e4f114

### Issue
As far as I can tell (based off the version number), I have an up-to-date version of the app. Nonetheless, my UI looks significantly different than the screenshots in the README (note multiple buttons are missing in the recipe view):
![image](https://user-images.githubusercontent.com/8076094/91070532-22d20380-e637-11ea-86d1-c0b302958049.png)

Do I have to enable those buttons somehow or are the README screenshots outdated? And if it's the latter: why were the buttons removed? I understand that the menu contains too many options for each to be its own button, but I feel that editing and perhaps printing are used commonly enough to have their own separate icons.

### `.env`
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=
POSTGRES_DB=djangodb

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0


# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=1
```

### `docker-compose.yml`
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
```
