### ISSUE TITLE
Images not loading / working

### ISSUE THREAD

**Issue by SupaYoshi** [vabene1111/recipes#241]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version:  0.11.1

### Issue
Images in recipes are not working, they are visible in the mount, but not in the directory

### `.env`
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=secret

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=secret
POSTGRES_DB=djangodb

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0


# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=1

```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```


  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - /home/beheerder/docker/recipes/.env
    volumes:
      - /home/beheerder/docker/recipes/staticfiles:/opt/recipes/staticfiles
      - /home/beheerder/docker/recipes/mediafiles:/opt/recipes/mediafiles
      - /home/beheerder/docker/recipes/staticfiles:/static
      - /home/beheerder/docker/recipes/mediafiles:/media

    depends_on:
      - db_recipes

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_recipes.entrypoints=http"
      - "traefik.http.routers.web_recipes.rule=Host(`recipes.battlecruiser.nl`)"
      - "traefik.http.middlewares.web_recipes-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.web_recipes.middlewares=web_recipes-https-redirect"
      - "traefik.http.routers.web_recipes-secure.entrypoints=https"
      - "traefik.http.routers.web_recipes-secure.rule=Host(`recipes.battlecruiser.nl`)"
      - "traefik.http.routers.web_recipes-secure.tls=true"
      - "traefik.http.routers.web_recipes-secure.tls.certresolver=http"
      - "traefik.http.routers.web_recipes-secure.service=web_recipes"
      - "traefik.http.services.web_recipes.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik_proxy"

    networks:
      - traefik_proxy



  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
#    ports:
#      - 8085:80
    env_file:
      - /home/beheerder/docker/recipes/.env
    volumes:
      - /home/beheerder/docker/recipes/nginx/conf.d:/etc/nginx/conf.d
      - /home/beheerder/docker/recipes/staticfiles:/static
      - /home/beheerder/docker/recipes/mediafiles:/media
    networks:
      - traefik_proxy

  db_recipes:
    restart: always
    image: postgres:11-alpine

    volumes:
      - /home/beheerder/docker/recipes/postgresql:/var/lib/postgresql/data
    env_file:
      - /home/beheerder/docker/recipes/.env
    networks:
      - traefik_proxy
```
