### ISSUE TITLE
Docker Image Doesn't Support Windows

### ISSUE THREAD

**Issue by BradleyDS2** [vabene1111/recipes#245]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: docker-compose.yml states `version: "3"`

### Bug description

Receive the following error from docker when trying to docker-compose up with the provided basic docker-compose file

```
db_recipes_1     | running bootstrap script ... 2020-12-14 12:17:05.929 UTC [53] FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions
db_recipes_1     | 2020-12-14 12:17:05.929 UTC [53] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

Due to docker being unable to chown mounted folders on Windows hosts, and the dev response being 'Docker is not a virtual machine', this is unlikely to be fixed on Dockers end (ongoing issue since 2016 https://github.com/docker/for-win/issues/39 )

This looks like it could be fixed by using MariaDB like #73 has suggested adding previously, and as linuxserver images tend to. Example: https://hub.docker.com/r/linuxserver/bookstack

This would also fix the following potential future issue:
https://stackoverflow.com/questions/59395721/django-db-backends-postgresql-psycopg2-not-working-in-django-3-0

Could you please change the provided docker-compose.yml to be cross-platform?

**Comment by vabene1111** [comment]
so the easiest fix for now would be to just host postgres seperatly and set django to connect to it (trough the .env) or use sqlite.

but in the future allowing MariaDB might be something i can do (although it would be an unofficial/unsupported build as i do not have the time to test another deployment method with each update)

**Comment by BradleyDS2** [comment]
Did some changes, which I'm not confident worked, as the log printed
```
web_recipes_1    |   Applying sessions.0001_initial... OK
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "manage.py", line 15, in <module>
web_recipes_1    |     execute_from_command_line(sys.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
web_recipes_1    |     utility.execute()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
web_recipes_1    |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
web_recipes_1    |     self.execute(*args, **cmd_options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
web_recipes_1    |     output = self.handle(*args, **options)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
web_recipes_1    |     collected = self.collect()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 132, in collect
web_recipes_1    |     for original_path, processed_path, processed in processor:
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/whitenoise/storage.py", line 162, in post_process_with_compression
web_recipes_1    |     for name, compressed_name in self.compress_files(files_to_compress):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/whitenoise/storage.py", line 201, in compress_files
web_recipes_1    |     for compressed_path in compressor.compress(path):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/whitenoise/compress.py", line 82, in compress
web_recipes_1    |     yield self.write_data(path, compressed, ".gz", stat_result)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.8/site-packages/whitenoise/compress.py", line 124, in write_data
web_recipes_1    |     os.utime(filename, (stat_result.st_atime, stat_result.st_mtime))
web_recipes_1    | OSError: [Errno 6] No such device or address
web_recipes_1    | Done
web_recipes_1    | [2020-12-14 13:07:43 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_recipes_1    | [2020-12-14 13:07:43 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
```
Which makes me think it's using gunicorn, but in the env, GUNICORN_MEDIA=0


The following are my dockerfile and the changes I did to the .env:
```
version: "3"
services:
  db_recipes:
    image: linuxserver/mariadb
    container_name: recipes_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD={mysqlpassword}
      - TZ={Timezone}
      - MYSQL_DATABASE=db_recipes
      - MYSQL_USER=recipesapp
      - MYSQL_PASSWORD={mysqlpassword}
    volumes:
      - D:\Docker\recipes\db:/config
    restart: unless-stopped  
    

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - D:\Docker\recipes\staticfiles:/opt/recipes/staticfiles
      - D:\Docker\recipes\mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    ports:
      - 8923:8080
  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - D:\Docker\recipes\nginx\conf.d:/etc/nginx/conf.d
      - D:\Docker\recipes\staticfiles:/static
      - D:\Docker\recipes\mediafiles:/media
```
And for the .env:

```
#DB_ENGINE=django.db.backends.postgresql_psycopg2
#POSTGRES_HOST=db_recipes
#POSTGRES_PORT=5432
#POSTGRES_USER=djangodb
#POSTGRES_PASSWORD={postgrespassword}
#POSTGRES_DB=djangodb
DB_HOST=recipes_db
DB_DATABASE=db_recipes
DB_USERNAME=recipesapp
DB_PASSWORD={mysqlpassword}
```
