### ISSUE TITLE
Plain docker-compose nginx issues

### ISSUE THREAD

**Issue by Lombra** [vabene1111/recipes#256]
### Version
Version: 0.11.2

### Issue
Had some issues getting the plain docker-compose up and running. Managed to access the service by using the app URL directly. Could only see this error relating to nginx:
```
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
```
Then I discovered that I'm supposed to download an nginx configuration file, as well. (couldn't find any mention of that in the docs?) So I downloaded [that](https://github.com/vabene1111/recipes/blob/develop/docs/docker/plain/nginx/conf.d/Recipes.conf). The above error remains, but now I'm also getting the following:
```
nginx_recipes_1  | 2020/12/15 20:56:30 [emerg] 1#1: host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:14
nginx_recipes_1  | nginx: [emerg] host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:14
```
Am I missing this default.conf file from somewhere, or is it something else?

### `.env`
```
DEBUG=0

ALLOWED_HOSTS=*

SECRET_KEY=

DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=wut
POSTGRES_DB=djangodb

SHOPPING_MIN_AUTOSYNC_INTERVAL=5

GUNICORN_MEDIA=0

REVERSE_PROXY_AUTH=0

COMMENT_PREF_DEFAULT=1
```

### `docker-compose.yml`
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 808:80
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
```
