### ISSUE TITLE
Hosting with traefik + sub-path README

### ISSUE THREAD

**Issue by incaseoftrouble** [vabene1111/recipes#266]
Hi,

It took me quite some time to figure out how to host this under a sub-path, so I thought I might share this info for others; maybe you can integrate it into the README / examples.

My setup is docker-compose / traefik / apache / recipes. Swapping out apache for nginx should be straightforward.

Relevant parts:

docker-compose:
```yml
  apache:
    # omitting other config
    volumes:
      - ./recipes/static:/var/www/recipes/static:ro
      - ./recipes/media:/var/www/recipes/media:ro
    labels:
      traefik.enable: true
      traefik.http.routers.apache-recipes.rule: Host(`<host>`) && PathPrefix(`/<www path>`)
      traefik.http.routers.apache-recipes.entrypoints: http
      traefik.http.routers.apache-recipes.service: apache
      traefik.http.services.apache.loadbalancer.server.port: 80
      traefik.http.services.apache.loadbalancer.server.scheme: http
...

  recipes:
    volumes:
      - ./recipes/static:/opt/recipes/staticfiles:rw
      - ./recipes/media:/opt/recipes/mediafiles:rw
    environment:
      # all the other env
      - SCRIPT_NAME=/<sub path>
      - STATIC_URL=/<www path>/static/
      - MEDIA_URL=/<www path>/media/
    labels:
      traefik.enable: true
      traefik.http.routers.recipes.rule: Host(`<host>`) && PathPrefix(`/<sub path>`)
      traefik.http.routers.recipes.entrypoints: http
      traefik.http.services.recipes.loadbalancer.server.port: 8080
      traefik.http.services.recipes.loadbalancer.server.scheme: http
```

apache: 
```
  Alias /<www path>/static/ /var/www/recipes/static/
  Alias /<www path>/media/ /var/www/recipes/media/
  <Directory "/var/www/recipes/">
    Require all granted
  </Directory>
```

I used two paths `<sub path>` and `<www path>` for simplicity. In my case I have `<sub path> = recipes` and `<www path> = serve/recipes`. One could also change the matching rules of traefik to have everything under one path.

I left out the TLS config in this example for simplicty.

**Comment by vabene1111** [comment]
thank you! We are getting to a point where we have quite a few "unoffical" setup instructions. Maybe i will create a section in the discussions area or maybe i will add this to the setup examples.

**Comment by incaseoftrouble** [comment]
If you want I could create a fully functional configuration (i.e. something that `cd docs/docker/traefik-subpath-apache && docker-compose up -d` yields a functional instance)

**Comment by vabene1111** [comment]
hmm you mean by cloning the whole repo first ? 

this is not really in the sense of the installation process that is common at this point. But that said the installation process isn't great.

I guess for now the instructions above suffice. At some point the installation process will be revisited and we will think about this as well.

**Comment by vabene1111** [comment]
i have added your example to the new docs. Feel free to open a PR (or issue) if you want anything changed or want to improve it further

**Comment by JSAnyone** [comment]
Is it really necessary to expose the webserver-service (Nginx/Apache) and the recipes-service with Traefik?
The [default example here](https://docs.tandoor.dev/install/docker/) only exposes the webserver-service, but not the recipes-service I got it right.

**Comment by incaseoftrouble** [comment]
IIRC it is not necessary, but I let apache serve the static data.

**Comment by JSAnyone** [comment]
Hi,
I just don’t get it to work. Tandoor is running behind `/recipes/` as expected, but there are some some requests to `/api/` instead of `/recipes/api` which of course doesn’t work.

The relevant parts in my .env:
```
SCRIPT_NAME=/recipes
STATIC_URL=/recipes/static/
MEDIA_URL=/recipes/media/
```

The traefik labels:
```
- "traefik.enable=true"
- "traefik.http.routers.recipes-local.entrypoints=web"
- "traefik.http.routers.recipes-local.rule=Host(`192.168.10.3`)&&PathPrefix(`/recipes/`)"
```

Nginx-config:
```
server {
  listen 80;
  server_name localhost;

  client_max_body_size 128M;

  location /recipes/media/ {
    alias /media/;
  }
  location /recipes/static/ {
    alias /static/;
  }
  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://web_recipes:8080;
  }
}
```

**Comment by smilerz** [comment]
@JSAnyone you also need to set the lines below in your nginx config
```
    proxy_set_header X-Script-Name /recipes;
    proxy_cookie_path / /recipes;
```

(I'm actually not 100% sure about the proxy_cookie_path, but I'm assuming I put it there for a reason?)

**Comment by JSAnyone** [comment]
That‘s it, Thanks!
Maybe it‘s helpful to add this to the documentation as a nginx-example?

 .env:
```
SCRIPT_NAME=/recipes
STATIC_URL=/recipes/static/
MEDIA_URL=/recipes/media/
```

Nginx-config (`/var/lib/docker/volumes/yourvolumename/_data/Recipes.conf`):
```
server {
  listen 80;
  server_name localhost;

  client_max_body_size 128M;

  # serve media files
  location /recipes/media/ {
    alias /media/;
  }
  location /recipes/static/ {
    alias /static/;
  }
  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://web_recipes:8080;
    proxy_set_header X-Script-Name /recipes;
    proxy_cookie_path / /recipes;
  }
}
```

docker-compose.yml:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
- postgres-storage:/var/lib/postgresql/data
    env_file:
- ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
- ./.env
    volumes:
- staticfiles-storage:/opt/recipes/staticfiles
- nginxconfig-storage:/opt/recipes/nginx/conf.d
- mediafiles-storage:/opt/recipes/mediafiles
    depends_on:
- db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
#   ports:
#     - 8080:80
    env_file:
- ./.env
    depends_on:
- web_recipes
    volumes:
- nginxconfig-storage:/etc/nginx/conf.d:ro
- staticfiles-storage:/static
- mediafiles-storage:/media
    labels:
- "traefik.enable=true"
- "traefik.http.routers.recipes-local.entrypoints=web"
- "traefik.http.routers.recipes-local.rule=Host(`IP`)&&PathPrefix(`/recipes/`)"

volumes:
  postgres-storage:
  nginxconfig-storage:
  staticfiles-storage:
  mediafiles-storage:
```
