### ISSUE TITLE
Problem starting/ accessing server

### ISSUE THREAD

**Issue by RustyRin** [vabene1111/recipes#33]
Bear with me a bit, this is literally my first time using Docker and also first experience in any non-plug and play server software.

I am currently having a problem accessing the server on every device but my machine that I'm hosting it on, but even then none of the CSS loads. 

I'm trying to get this to work over my public IP address to that friends and family can use it as well.
Tell me if there is anything that I could give you that would make this easier to solve

Thank you!

**Comment by vabene1111** [comment]
ok so first do `docker-compose ps` to see if the services are actually running.

If they are make sure you have run the `update.sh` script which is used to collect the static resources and server them over nginx directly (that is most likely the problem).

if that does not help please post the output of the log `ds logs -f` and your `docker-compose.yml` and `.env` file (make sure to **redact/remove/replace any secrets first**)

Dont be afraid of asking, i want this to be installable as easily as possible and feedback from people who are not experienced with docker deployments is very interesting in that regard. In the end i am no docker expert as well so there are most likely many things that can be improved.

**Comment by RustyRin** [comment]
`docker-compose ps` shows that db, nginx and web recipes are all running.

`update.sh` says 
```Starting recipes_db_recipes_1 ... done
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, cookbook, sessions
Running migrations:
  No migrations to apply.
Starting recipes_db_recipes_1 ... done

0 static files copied to '/Recipes/staticfiles', 450 unmodified.
```

I don't know what my `ds logs -f` would be, but my `docker-compose.yml` is
```version: "3"
services:
  db_recipes:
    restart: always
    image: "postgres:11-alpine"
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env
    networks:
    - default

  web_recipes:
    build: .
    restart: always
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    volumes:
    - .:/Recipes
    depends_on:
    - db_recipes
    networks:
    - default

  nginx_recipes:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
    networks:
    - default
    - nginx-proxy

networks:
  default:
  nginx-proxy:
    external:
      name: nginx-proxy```

Well, I'll happily become your guinea pig 😎

**Comment by vabene1111** [comment]
Do you run an aditional nginx proxy docker container in front of the recipes container ?
I have added this as the default as i (and i think many others) run many dockler applications on one host so that seamed reasonable. 

If you do not do so (and if you do not know what i am talking about than you dont) you have to remove the networks section of all three containers and at the bottom of the compose file like this 

```
services:
  db_recipes:
    restart: always
    image: "postgres:11-alpine"
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env

  web_recipes:
    build: .
    restart: always
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    volumes:
    - .:/Recipes
    depends_on:
    - db_recipes

  nginx_recipes:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
```
I dont currently have the time to test this but it should work.

**Comment by vabene1111** [comment]
Also interesting that you say you have to add your IP to the authorized hosts, the default should allow any host to run it ...

I would also recommend not to use your host pc's password as a DB password as it is a major security risk saving it unencrypted on a drive, especially on a web server :)

**Comment by RustyRin** [comment]
I replace my `docker-compose.yml` with that you gave me and removed the allowed host IP and replaced it with `*`.
I then started it up with `docker-compose up` and got two prints that I'm assuming are warnings  
``nginx_recipes_1  | 2020/02/27 02:41:54 [emerg] 1#1: host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:19``
``nginx_recipes_1  | nginx: [emerg] host not found in upstream "web_recipes" in /etc/nginx/conf.d/Recipes.conf:19``

The page is still only accessible from the 172 Docker IP address and still cannot reach or find the CSS and JS.
Also I don't think I properly said it but this 172.xx.x.x Docker address is not a local address that my modem can see and it isn't my public address.

**Comment by vabene1111** [comment]
That is interesting. The error message and the fact that you have to specify the IP address explictly indicates that something is wrong with the docker network but to be hones i dont really know what. 

Do you have other services running on that server and if so on which ports ? 
You say you dont have any other docker containers running is that right ?
Do you have any configuration with iptables or anything else that could mix up routing on the server ?

**Comment by vabene1111** [comment]
ok so i have just tested this config on my server and it works, can you try that ?

```
version: "3"
services:
  db_recipes:
    restart: always
    image: "postgres:11-alpine"
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env
    networks:
    - default

  web_recipes:
    build: .
    restart: always
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    volumes:
    - .:/Recipes
    depends_on:
    - db_recipes
    networks:
    - default

  nginx_recipes:
    image: "nginx"
    restart: always
    env_file:
    - ./.env
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./staticfiles:/static
    - ./mediafiles:/media
    ports:
    - 8080:80
    networks:
    - default
    depends_on:
    - web_recipes

```
simply change the port on the nginx container to match the port you want to expose the service on.

I would recommend using another nginx as a reverse proxy in front to allow multiple services on one machine an also to add a SSL certificate.
