### ISSUE TITLE
static files not found

### ISSUE THREAD

**Issue by palitu** [vabene1111/recipes#36]
I love the idea of this, however i constantly have issues installing it.

I would typically expect that a docker-compose file gets everything started to a default installation, without the nginx reverse proxy.

My current compose looks like this:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: "postgres:11-alpine"
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    env_file:
    - ./.env
    networks:
    - default

  web_recipes:
    build: .
    restart: unless-stopped
    env_file:
    - ./.env
    command: "gunicorn --bind 0.0.0.0:8080 recipes.wsgi"
    volumes:
    - .:/Recipes
    depends_on:
    - db_recipes
    networks:
    - default
    ports:
    - 5678:8080

networks:
  default:
```

I managed to create the admin user, but the system does not load any CSS, and it now looks like this:
![image](https://user-images.githubusercontent.com/6634784/76155822-ad2bb700-612c-11ea-97c2-6036bf8d1a87.png)

and i have the following errors:
```
web_recipes_1  | [2020-03-08 03:03:51 +0000] [1] [INFO] Starting gunicorn 20.0.4
web_recipes_1  | [2020-03-08 03:03:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
web_recipes_1  | [2020-03-08 03:03:51 +0000] [1] [INFO] Using worker: sync
web_recipes_1  | [2020-03-08 03:03:51 +0000] [9] [INFO] Booting worker with pid: 9
web_recipes_1  | Not Found: /static/themes/flatly.min.css
web_recipes_1  | Not Found: /static/themes/select2-bootstrap-theme.css
web_recipes_1  | Not Found: /static/fontawesome/fontawesome_all.min.css
web_recipes_1  | Not Found: /static/themes/select2-bootstrap-theme.css
web_recipes_1  | Not Found: /static/fontawesome/fontawesome_all.min.css
web_recipes_1  | Not Found: /static/favicon.png
```

any help with the setup would be appreciated!
