### ISSUE TITLE
Oauth

### ISSUE THREAD

**Issue by cesarblancg** [vabene1111/recipes#365]
### Version
Version:  beta

### Issue
When I try to login with Oatuh method, appears error 500. I had an Nginx container that handles all the 80 and 443 petitions and redirects them to the appropriate container(in this case, 2312). All my containers work well and the rest of the recipes project works fine. I can't see anything on the logs file.

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=

# your default timezone
TIMEZONE=Europe/Madrid

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=

# the default value for the user preference 'fractions' (enable/disable fraction support)
# when unset: 0 (disabled)
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=0

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=10

# Default for user setting sticky navbar
#STICKY_NAV_PREF_DEFAULT=1

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0

SOCIAL_PROVIDERS=allauth.socialaccount.providers.github,allauth.socialaccount.providers.nextcloud
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
version: "2.1"
services:

  db_recipes:
    container_name: db_recipes
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - /media/rasp_hdd/config/recipes/postgre:/var/lib/postgresql/data
    env_file:
      - /media/rasp_hdd/config/recipes/env.env

  web_recipes:
    image: vabene1111/recipes:beta
    container_name: web_recipes
    restart: unless-stopped
    env_file:
      - /media/rasp_hdd/config/recipes/env.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - /media/rasp_hdd/config/recipes/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    container_name: nginx_recipes
    restart: unless-stopped
    ports:
      - 2312:80
    env_file:
      - /media/rasp_hdd/config/recipes/env.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - /media/rasp_hdd/config/recipes/mediafiles:/media

  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Madrid
      - URL=
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=
      - EMAIL=
    volumes:
      - /media/rasp_hdd/config/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

volumes:
  nginx_config:
  staticfiles:
```
