### ISSUE TITLE
Fatal Python error: pyinit_main: can't initialize time

### ISSUE THREAD

**Issue by dekiesel** [vabene1111/recipes#447]
### Version
Docker version 0.14.3

### Issue
Starting the new container errors out

### `env`
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=12recipes3
POSTGRES_DB=djangodb

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0


# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=1
```

### `docker-compose`
```
version: "3"
services:
  db_recipes:
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - ${DBDATA}:/var/lib/postgresql/data
    env_file:
      - ./environment.env

  web_recipes:
    #image: vabene1111/recipes:0.11.2
    #image: vabene1111/recipes:0.12.1
    #image: vabene1111/recipes:0.13.0
    image: vabene1111/recipes:0.14.3
    restart: unless-stopped
    volumes:
      - ${RSTATIC}:/opt/recipes/staticfiles
      - ${RMEDIA}:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    env_file:
      - ./environment.env

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 680:80
    volumes:
      - ${NCONF}:/etc/nginx/conf.d
      - ${RSTATIC}:/static
      - ${RMEDIA}:/media
    env_file:
      - ./environment.env
```

### `output`

```
web_recipes_1    | Updating database
db_recipes_1     |
db_recipes_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_recipes_1     |
db_recipes_1     | 2021-02-22 02:00:43.058 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes_1     | 2021-02-22 02:00:43.058 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_recipes_1     | 2021-02-22 02:00:43.065 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2021-02-22 02:00:43.124 UTC [21] LOG:  database system was shut down at 2021-02-22 02:00:04 UTC
db_recipes_1     | 2021-02-22 02:00:43.141 UTC [1] LOG:  database system is ready to accept connections
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6fa2390 (most recent call first):
web_recipes_1    | <no Python frame>
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
web_recipes_1    | Current thread 0xb6fac390 (most recent call first):
web_recipes_1    | <no Python frame>
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6f6c390 (most recent call first):
web_recipes_1    | <no Python frame>
web_recipes_1    | Done
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6f31390 (most recent call first):
web_recipes_1    | <no Python frame>
recipes_web_recipes_1 exited with code 0
web_recipes_1    | Updating database
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6fa2390 (most recent call first):
web_recipes_1    | <no Python frame>
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6fac390 (most recent call first):
web_recipes_1    | <no Python frame>
web_recipes_1    | Fatal Python error: pyinit_main: can't initialize time
web_recipes_1    | Python runtime state: core initialized
web_recipes_1    | PermissionError: [Errno 1] Operation not permitted
web_recipes_1    |
web_recipes_1    | Current thread 0xb6f6c390 (most recent call first):
web_recipes_1    | <no Python frame>
```

Version 0.13.0 works, any idea what I am doing wrong? Thank you for your help!
