### ISSUE TITLE
Pictures in recipes are not shown

### ISSUE THREAD

**Issue by kampsj** [vabene1111/recipes#470]
### Version
Version: 0.14.5

### Issue
Pictures are not shown on the recipe detail page. (See screenshot)
![no_image](https://user-images.githubusercontent.com/36105509/109393836-3d59a200-7924-11eb-8865-ba785beba8f5.png)
Pictures on the search page are being shown.
![image_showing](https://user-images.githubusercontent.com/36105509/109393852-51050880-7924-11eb-8673-f95e11914f77.png)

Inspecting both pages, I can see that for the detailed page an absolute path (I think?) to the image is created. This path is not working since it is omitting the port it is hosted on.

Detailed page (image not showing):
```
<img src="http://localhost/media/recipes/494e72ef-7512-4862-bce9-a722a4ee7089_4.png" alt="Recept afbeelding" class="img img-fluid rounded" style="max-height: 30vh;">
```
Search page (images are showing):
```
<img src=" /media/recipes/494e72ef-7512-4862-bce9-a722a4ee7089_4.png" alt="Recept afbeelding" class="card-img" style="object-fit: cover;height: 130px">
```

### `.env`
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=[redacted]

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=[redacted]
POSTGRES_DB=djangodb

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0


# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=1

```

### `docker-compose.yml`
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./db_backup:/opt/recipes/db_backup
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
      - ./db_backup:/db_backup
```
