### ISSUE TITLE
Shopping List Does Not Complete Transaction

### ISSUE THREAD

**Issue by uriscoes** [vabene1111/recipes#481]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: 0.14.5

### Bug description
When attempting to generate a shopping list, the shopping list page displays the spinning loading dots indefinitely.
No shopping list is generated. It is impossible to create shopping lists.

### Steps to Reproduce
Follow installation guide for the "plain" docker-compose.yml
Run docker-compose up -d 
Import a recipe from the web (suggested recipe: https://www.dinneratthezoo.com/breakfast-egg-muffins/)
Attempt to generate a shopping list using this recipe.

### docker-compose.yml file
```

version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 9001:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config:
  staticfiles:



```

**Comment by uriscoes** [comment]
### .env file
```
# only set this to true when testing/debugging`
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0
# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=*************************************
# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=America/Chicago

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=***************************
POSTGRES_DB=djangodb

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
#STICKY_NAV_PREF_DEFAULT=1

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# SOCIAL_PROVIDERS = allauth.socialaccount.providers.github, allauth.socialaccount.providers.nextcloud,}

```

**Comment by vabene1111** [comment]
interesting problem 🤔 

can you provide me with the output of `docker-compose logs` ?

**Comment by uriscoes** [comment]
Hey let first me say this is the greatest implementation of recipe management software I have ever seen. Thank you vabene1111 for writing this and may God bless you.

Second, the container seems to behave once the original containers and volumes were erased and the nginx_recipes port was set to 80:80 instead of 9001:80.
```
 nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80 (instead of 9001:80)
```
I became distracted when I learned that docker bypasses UFW firewall rules and did not collect docker-compose logs for you. Once I sort out an acceptable solution to docker and UFW, I'll try again.
