### ISSUE TITLE
Paprika Format Import Errors

### ISSUE THREAD

**Issue by Seversonic** [vabene1111/recipes#506]
### Version
Version: 0.14.5

Paprika Version:
3.2.0

[cookiesExport 2021-03-25 09.23.21.paprikarecipes.zip](https://github.com/vabene1111/recipes/files/6205923/cookiesExport.2021-03-25.09.23.21.paprikarecipes.zip)

### Bug description
Attempting to import .paprika recipe (single recipe and whole recipe book [145 recipes]) but getting some errors

Single recipe import error
```
Request Method: | POST
-- | --
https://recipes.example.com/import/
3.1.7
UnicodeDecodeError
'utf-8' codec can't decode byte 0xf0 in position 10: invalid continuation byte
/opt/recipes/cookbook/integration/paprika.py, line 24, in get_recipe_from_file
/opt/recipes/venv/bin/python
3.8.8
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/opt/recipes/venv/lib/python3.8/site-packages']
Thu, 25 Mar 2021 16:27:38 +0100


Unicode error hint

The string that could not be encoded/decoded was: �JyR6�


```

Whole book import error
```
Request Method: | POST
-- | --
https://recipes.example.com/import/
3.1.7
AttributeError
'_io.BufferedRandom' object has no attribute 'getvalue'
/usr/local/lib/python3.8/tempfile.py, line 468, in __getattr__
/opt/recipes/venv/bin/python
3.8.8
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python38.zip',  '/usr/local/lib/python3.8',  '/usr/local/lib/python3.8/lib-dynload',  '/opt/recipes/venv/lib/python3.8/site-packages']
Thu, 25 Mar 2021 16:31:34 +0100
```
Single recipe file attached

Docker compose I am using

```
version: "3"
services:
  db_recipes:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  recipes:
    image: vabene1111/recipes
    container_name: recipes
    environment:
      - SECRET_KEY=YOUR_SECRET_KEY
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
    depends_on:
      - db_recipes
    volumes:
      - /srv/dev-disk-by-label-codex/docker/configs/recipes/staticfiles:/opt/recipes/staticfiles
      - /srv/dev-disk-by-label-codex/docker/configs/recipes/mediafiles:/opt/recipes/mediafiles  
    labels:
      - "traefik.enable=true"
      #- "traefik.http.routers.recipes-http.rule=Host(`recipes.home`)"
      #- "traefik.http.routers.recipes-http.entrypoints=web"
      
      - "traefik.http.routers.recipes.rule=(Host(`recipes.home`) || Host(`recipes.example.com`))"
      - "traefik.http.routers.recipes.entrypoints=https"
      #- "traefik.http.routers.traefik.middlewares=auth"
      #- "traefik.http.routers.jellyfin.service=api@internal"
      - "traefik.http.routers.recipes.tls=true"
      # Uncomment to fetch Let's Encrypt certificates.
      # Make sure you set up DNS records and they point to your IP.
      #- "traefik.http.routers.recipes-https.tls.certresolver=letsencrypt"
      
      

networks:
  default:
    external:
      name: traffic_default    
      
     
```
