### ISSUE TITLE
403 CSRF Error (AGAIN)

### ISSUE THREAD

**Issue by auanasgheps** [vabene1111/recipes#518]
## Issue
Hi, I'm trying to use Recipes with [Nginx proxy manager](https://nginxproxymanager.com/) using the following setup:

Nginx Proxy Manager > Recipes Nginx > Recipes Web App

I've configured Recipes Nginx using the provided config file and in fact works good.
When I connect in LAN pointing to Regipes Nginx everything works good (photos included).

However if I configure Nginx Proxy Manager to point to Recipes Nginx, nobody is able to login.
I believe there's something missing in Nginx Proxy Manager, but I can't figure it out. I also tried connecting straight to the Recipes Web app (exposing the port) but still getting the same error.

Enabling debug, the web browser shows 

```
Reason given for failure:

    Referer checking failed - https://recipes.mydomain.cloud:8080/accounts/login/?next=/search/ does not match any trusted origins.
```

## Setup Info
Version: 0.14.5
OS: Synology NAS w/ Docker

Other relevant information regarding your problem (proxies, firewalls, etc.)

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
I added my domain to `ALLOWED_HOSTS`
```
# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=recipes.mydomain.cloud
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```yml
version: "2"
services:
  recipes-db:
    restart: unless-stopped
    image: postgres:11-alpine
    container_name: recipes-db
    volumes:
        - /volume2/docker/recipes/db:/var/lib/postgresql/data
    env_file: /data/compose/recipes-env/recipes.env
    networks:
      - rete  

  recipes-app:
    image: vabene1111/recipes
    restart: unless-stopped
    container_name: recipes-app
    env_file: /data/compose/recipes-env/recipes.env
    volumes:
        - /volume2/docker/recipes/staticfiles:/opt/recipes/staticfiles
        - /volume2/docker/recipes/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - recipes-db
    networks:
      - rete  
 
  recipes-nginx:
    image: nginx:mainline-alpine
    restart: always
    container_name: recipes-nginx
    ports:
      - 2310:80
    env_file: /data/compose/recipes-env/recipes.env
    depends_on:
      - recipes-app
    volumes:
      - /volume2/docker/recipes/nginx_config:/etc/nginx/conf.d:ro
      - /volume2/docker/recipes/staticfiles:/static
      - /volume2/docker/recipes/mediafiles:/media
    networks:
      - rete  
  
networks:
    rete:
        external:
            name: rete
```

### Logs
From Docker - Recipes Web App:

[2021-04-03 15:16:33 +0000] [14] [INFO] Booting worker with pid: 14
Forbidden (Referer checking failed - https://recipes.mydomain.cloud:8080/accounts/login/?next=/search/ does not match any trusted origins.): /accounts/login/
