### ISSUE TITLE
updating docker image overwrote database

### ISSUE THREAD

**Issue by LennyPenny** [vabene1111/recipes#562]
### Version
Please provide your current version (can be found on the system page since v0.8.4)
Version: `0.15.2`

### Bug description
Hey, 
I just recreated my tandoor docker container to update from `0.15.1` to `0.15.2`. I did not change the db container. 
It seems that it completely threw the whole database away and created a new one. 
Is this intended behavior? Is there a different path to upgrade docker installations?

**Comment by vabene1111** [comment]
This is definitly not intendet. 

Are you running the default setup ? 
What is your docker compose ?

Data usually gets lost if you forget to mount a volume or in case of this application change the default configuration somehow so that the default mounts no longer work

**Comment by LennyPenny** [comment]
```
---
- name: Create tandoor-db container
  become: yes
  become_user: root
  docker_container:
    image: postgres:13-alpine
    name: tandoordb
    hostname: tandoordb
    volumes:
      - "./tandoor-db:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "{{ postgres.user }}"
      POSTGRES_PASSWORD: "{{ postgres.password }}"
    networks:
      - name: tandoor-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "{{ postgres.user }}"]
      interval: 10s
      start_period: 30s
    labels:
      traefik.enable: "false"
    state: started
    restart_policy: always
- name: Create tandoor container
  become: yes
  become_user: root
  docker_container:
    image: "vabene1111/recipes:0.15.2"
    name: "tandoor"
    volumes:
      - "./tandoor/staticfiles:/opt/recipes/staticfiles"
      - "./tandoor/mediafiles:/opt/recipes/mediafiles"
    env:
      POSTGRES_USER: "{{ postgres.user }}"
      POSTGRES_PASSWORD: "{{ postgres.password }}"
      POSTGRES_HOST: "tandoordb"
      POSTGRES_PORT: "5432"
      SECRET_KEY: "{{ tandoor.secret_key }}"
    networks:
      - name: tandoor-net
    labels:
      traefik.enable: "true"
      traefik.http.routers.tandoor.rule: "xxx"
      traefik.http.routers.tandoor.entrypoints: "websecure"
      traefik.http.routers.tandoor.tls.certresolver: "myresolver"
      traefik.http.routers.tandoor.service: "tandoor"
      traefik.http.services.tandoor.loadbalancer.server.port: "8080"
      traefik.docker.network: "tandoor-net"
    state: started
    restart_policy: always
```

(this is ansible, noy docker compose, but it's should be obvious enough whats going on)
