### ISSUE TITLE
Recipe Images Not Loading

### ISSUE THREAD

**Issue by BradleyDS2** [vabene1111/recipes#615]
## Issue
Images don't appear, and their URLs lead to a 404.
![image](https://user-images.githubusercontent.com/2174921/118355130-e0c86380-b5b1-11eb-8789-2debbc60af49.png)
![image](https://user-images.githubusercontent.com/2174921/118355136-e8880800-b5b1-11eb-9396-18ae8c551ec9.png)

## Setup Info
Version: 0.15.2
OS: Windows Server 2019

Other relevant information regarding your problem (proxies, firewalls, etc.)
Accessing the URL on the host machine

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
SECRET_KEY=REDACTED

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Australia/Sydney

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
#DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
#POSTGRES_HOST=db_recipes
#POSTGRES_PORT=5432
#POSTGRES_USER=djangouser
#POSTGRES_PASSWORD=
#POSTGRES_DB=djangodb
#DB_ENGINE=django.db.backends.sqlite3


# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=1

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
#STICKY_NAV_PREF_DEFAULT=1

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0



# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# SOCIAL_PROVIDERS = allauth.socialaccount.providers.github, allauth.socialaccount.providers.nextcloud,

# Should a newly created user from a social provider get assigned to the default space and given permission by default ?
# ATTENTION: This feature might be deprecated in favor of a space join and public viewing system in the future
# default 0 (false), when 1 (true) users will be assigned space and group
# SOCIAL_DEFAULT_ACCESS = 1

# if SOCIAL_DEFAULT_ACCESS is used, which group should be added
# SOCIAL_DEFAULT_GROUP=guest
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
version: "3"
services:
  web_recipes:
    image: vabene1111/recipes
    restart: unless-stopped
    ports:
      - 9434:8080
    env_file:
      - ./.env
    volumes:
      - ./data/staticfiles:/opt/recipes/staticfiles
      - ./data/nginx_config:/opt/recipes/nginx/conf.d
      - ./data/mediafiles:/opt/recipes/mediafiles
      - ./data\db.sqlite:/opt/recipes/db.sqlite

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - ./data/nginx_config:/etc/nginx/conf.d:ro
      - ./data/staticfiles:/static
      - ./data/mediafiles:/media
      - ./data\db.sqlite:/opt/recipes/db.sqlite
```
