### ISSUE TITLE
Uploading images doesn't work properly.

### ISSUE THREAD

**Issue by samr28** [vabene1111/recipes#97]
When I try to add an image to a recipe, it doesn't seem to map properly and ends up just showing the alt text. I've tried with a couple of different images (png & jpg) and they all have this problem. I've attached screenshots as well as one of the images I tried.

I thought this could be an issue with the nginx proxy I setup but it seems to also happen when I remove the proxy and just connect to `localhost`.

Test image: https://knowpathology.com.au/app/uploads/2018/07/Happy-Test-Screen-01.png
![image](https://user-images.githubusercontent.com/3688992/83786241-10f44c00-a658-11ea-8ca7-290e7e22ef42.png)
![image](https://user-images.githubusercontent.com/3688992/83786276-1baee100-a658-11ea-88d1-0b3924adefc8.png)
![image](https://user-images.githubusercontent.com/3688992/83786363-37b28280-a658-11ea-95c5-36484cfb49fa.png)

**Comment by vabene1111** [comment]
ah yes, the problem ist with media serving. can you post your docker compose file and the .env file here ? (obvioulsy remove/change any passwords or secret keys please). It is most likely related to the changes mentioned [here](https://github.com/vabene1111/recipes/releases/tag/0.8.1), maybe i forgot an edge case.

**Comment by vabene1111** [comment]
also please check: if you run `docker-compose logs -f | grep nginx` does it show you any nginx errors ?

**Comment by samr28** [comment]
> also please check: if you run `docker-compose logs -f | grep nginx` does it show you any nginx errors ?

So actually there is no nginx running with docker. I have nginx installed on the host machine which is just proxying to the docker container (localhost:3003). I just went in and updated my nginx config to match [this](https://github.com/vabene1111/recipes/blob/master/docs/docker/nginx-proxy/nginx/conf.d/Recipes.conf) but it still didn't seem to work. I was missing the `location /media/` block but it didn't seem to change anything when added.

docker-compose.yml
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    container_name: recipes-postgres
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    image: vabene1111/recipes
    container_name: recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    ports:
      - 3003:8080
    depends_on:
      - db_recipes
    networks:
      - default
```

.env
```
# only set this to true when testing/debugging
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=<removed>

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=<removed>
POSTGRES_DB=djangodb

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
GUNICORN_MEDIA=0
```

**Comment by vabene1111** [comment]
Does your nginx have the media folder mounted as described in this example 
```
nginx_recipes:
      image: nginx:mainline-alpine
      restart: always
      env_file:
        - ./.env
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./staticfiles:/static
        - ./mediafiles:/media
      networks:
        - default
        - nginx-proxy
```

technically if you have a nginx server in front of all requests anyway you might as well turn on the `GUNICORN_MEDIA` variable to have gunicorn serve the media files to your nginx proxy. I am no expert on this though so it might not be the perfect solution. 

As nginx does not add too much overhead another fix would be to just run a second nginx inside the docker-compose and have that one expose port 3003 to your central reverse proxy nginx (i have this setup running for many applications and it works perfectly fine without consuming to much CPU)
